#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BAL_DLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QL_TracNghiem")]
	public partial class DB_QLTracNghiemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_BaiThi(Table_BaiThi instance);
    partial void UpdateTable_BaiThi(Table_BaiThi instance);
    partial void DeleteTable_BaiThi(Table_BaiThi instance);
    partial void InsertTable_CauHoi(Table_CauHoi instance);
    partial void UpdateTable_CauHoi(Table_CauHoi instance);
    partial void DeleteTable_CauHoi(Table_CauHoi instance);
    partial void InsertTable_DapAn(Table_DapAn instance);
    partial void UpdateTable_DapAn(Table_DapAn instance);
    partial void DeleteTable_DapAn(Table_DapAn instance);
    partial void InsertTable_GiaoVien(Table_GiaoVien instance);
    partial void UpdateTable_GiaoVien(Table_GiaoVien instance);
    partial void DeleteTable_GiaoVien(Table_GiaoVien instance);
    partial void InsertTable_KetQua(Table_KetQua instance);
    partial void UpdateTable_KetQua(Table_KetQua instance);
    partial void DeleteTable_KetQua(Table_KetQua instance);
    partial void InsertTable_LoaiCauHoi(Table_LoaiCauHoi instance);
    partial void UpdateTable_LoaiCauHoi(Table_LoaiCauHoi instance);
    partial void DeleteTable_LoaiCauHoi(Table_LoaiCauHoi instance);
    partial void InsertTable_MonThi(Table_MonThi instance);
    partial void UpdateTable_MonThi(Table_MonThi instance);
    partial void DeleteTable_MonThi(Table_MonThi instance);
    partial void InsertTable_Nganh(Table_Nganh instance);
    partial void UpdateTable_Nganh(Table_Nganh instance);
    partial void DeleteTable_Nganh(Table_Nganh instance);
    partial void InsertTable_NguoiDung(Table_NguoiDung instance);
    partial void UpdateTable_NguoiDung(Table_NguoiDung instance);
    partial void DeleteTable_NguoiDung(Table_NguoiDung instance);
    partial void InsertTable_ThiSinh(Table_ThiSinh instance);
    partial void UpdateTable_ThiSinh(Table_ThiSinh instance);
    partial void DeleteTable_ThiSinh(Table_ThiSinh instance);
    #endregion
		
		public DB_QLTracNghiemDataContext() : 
				base(global::BAL_DLL.Properties.Settings.Default.QL_TracNghiemConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLTracNghiemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLTracNghiemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLTracNghiemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_QLTracNghiemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_BaiThi> Table_BaiThis
		{
			get
			{
				return this.GetTable<Table_BaiThi>();
			}
		}
		
		public System.Data.Linq.Table<Table_CauHoi> Table_CauHois
		{
			get
			{
				return this.GetTable<Table_CauHoi>();
			}
		}
		
		public System.Data.Linq.Table<Table_DapAn> Table_DapAns
		{
			get
			{
				return this.GetTable<Table_DapAn>();
			}
		}
		
		public System.Data.Linq.Table<Table_GiaoVien> Table_GiaoViens
		{
			get
			{
				return this.GetTable<Table_GiaoVien>();
			}
		}
		
		public System.Data.Linq.Table<Table_KetQua> Table_KetQuas
		{
			get
			{
				return this.GetTable<Table_KetQua>();
			}
		}
		
		public System.Data.Linq.Table<Table_LoaiCauHoi> Table_LoaiCauHois
		{
			get
			{
				return this.GetTable<Table_LoaiCauHoi>();
			}
		}
		
		public System.Data.Linq.Table<Table_MonThi> Table_MonThis
		{
			get
			{
				return this.GetTable<Table_MonThi>();
			}
		}
		
		public System.Data.Linq.Table<Table_Nganh> Table_Nganhs
		{
			get
			{
				return this.GetTable<Table_Nganh>();
			}
		}
		
		public System.Data.Linq.Table<Table_NguoiDung> Table_NguoiDungs
		{
			get
			{
				return this.GetTable<Table_NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<Table_ThiSinh> Table_ThiSinhs
		{
			get
			{
				return this.GetTable<Table_ThiSinh>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_BaiThi")]
	public partial class Table_BaiThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThiSinh;
		
		private string _MaMon;
		
		private string _NgayThi;
		
		private string _MaCauHoi;
		
		private string _LuaChon;
		
		private string _DapAn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThiSinhChanging(string value);
    partial void OnMaThiSinhChanged();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnNgayThiChanging(string value);
    partial void OnNgayThiChanged();
    partial void OnMaCauHoiChanging(string value);
    partial void OnMaCauHoiChanged();
    partial void OnLuaChonChanging(string value);
    partial void OnLuaChonChanged();
    partial void OnDapAnChanging(string value);
    partial void OnDapAnChanged();
    #endregion
		
		public Table_BaiThi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThiSinh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThiSinh
		{
			get
			{
				return this._MaThiSinh;
			}
			set
			{
				if ((this._MaThiSinh != value))
				{
					this.OnMaThiSinhChanging(value);
					this.SendPropertyChanging();
					this._MaThiSinh = value;
					this.SendPropertyChanged("MaThiSinh");
					this.OnMaThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="NChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuaChon", DbType="VarChar(20)")]
		public string LuaChon
		{
			get
			{
				return this._LuaChon;
			}
			set
			{
				if ((this._LuaChon != value))
				{
					this.OnLuaChonChanging(value);
					this.SendPropertyChanging();
					this._LuaChon = value;
					this.SendPropertyChanged("LuaChon");
					this.OnLuaChonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAn", DbType="VarChar(20)")]
		public string DapAn
		{
			get
			{
				return this._DapAn;
			}
			set
			{
				if ((this._DapAn != value))
				{
					this.OnDapAnChanging(value);
					this.SendPropertyChanging();
					this._DapAn = value;
					this.SendPropertyChanged("DapAn");
					this.OnDapAnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_CauHoi")]
	public partial class Table_CauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCauHoi;
		
		private string _NoiDungCauHoi;
		
		private string _MaLoaiCauHoi;
		
		private string _MaNguoiDung;
		
		private string _MaMon;
		
		private string _GhiChu;
		
		private EntitySet<Table_DapAn> _Table_DapAns;
		
		private EntityRef<Table_LoaiCauHoi> _Table_LoaiCauHoi;
		
		private EntityRef<Table_MonThi> _Table_MonThi;
		
		private EntityRef<Table_NguoiDung> _Table_NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauHoiChanging(string value);
    partial void OnMaCauHoiChanged();
    partial void OnNoiDungCauHoiChanging(string value);
    partial void OnNoiDungCauHoiChanged();
    partial void OnMaLoaiCauHoiChanging(string value);
    partial void OnMaLoaiCauHoiChanged();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public Table_CauHoi()
		{
			this._Table_DapAns = new EntitySet<Table_DapAn>(new Action<Table_DapAn>(this.attach_Table_DapAns), new Action<Table_DapAn>(this.detach_Table_DapAns));
			this._Table_LoaiCauHoi = default(EntityRef<Table_LoaiCauHoi>);
			this._Table_MonThi = default(EntityRef<Table_MonThi>);
			this._Table_NguoiDung = default(EntityRef<Table_NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCauHoi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDungCauHoi
		{
			get
			{
				return this._NoiDungCauHoi;
			}
			set
			{
				if ((this._NoiDungCauHoi != value))
				{
					this.OnNoiDungCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCauHoi = value;
					this.SendPropertyChanged("NoiDungCauHoi");
					this.OnNoiDungCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCauHoi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiCauHoi
		{
			get
			{
				return this._MaLoaiCauHoi;
			}
			set
			{
				if ((this._MaLoaiCauHoi != value))
				{
					if (this._Table_LoaiCauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCauHoi = value;
					this.SendPropertyChanged("MaLoaiCauHoi");
					this.OnMaLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					if (this._Table_NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._Table_MonThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NChar(30)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_CauHoi_Table_DapAn", Storage="_Table_DapAns", ThisKey="MaCauHoi", OtherKey="MaCauHoi")]
		public EntitySet<Table_DapAn> Table_DapAns
		{
			get
			{
				return this._Table_DapAns;
			}
			set
			{
				this._Table_DapAns.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LoaiCauHoi_Table_CauHoi", Storage="_Table_LoaiCauHoi", ThisKey="MaLoaiCauHoi", OtherKey="MaLoaiCauHoi", IsForeignKey=true)]
		public Table_LoaiCauHoi Table_LoaiCauHoi
		{
			get
			{
				return this._Table_LoaiCauHoi.Entity;
			}
			set
			{
				Table_LoaiCauHoi previousValue = this._Table_LoaiCauHoi.Entity;
				if (((previousValue != value) 
							|| (this._Table_LoaiCauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_LoaiCauHoi.Entity = null;
						previousValue.Table_CauHois.Remove(this);
					}
					this._Table_LoaiCauHoi.Entity = value;
					if ((value != null))
					{
						value.Table_CauHois.Add(this);
						this._MaLoaiCauHoi = value.MaLoaiCauHoi;
					}
					else
					{
						this._MaLoaiCauHoi = default(string);
					}
					this.SendPropertyChanged("Table_LoaiCauHoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_MonThi_Table_CauHoi", Storage="_Table_MonThi", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public Table_MonThi Table_MonThi
		{
			get
			{
				return this._Table_MonThi.Entity;
			}
			set
			{
				Table_MonThi previousValue = this._Table_MonThi.Entity;
				if (((previousValue != value) 
							|| (this._Table_MonThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_MonThi.Entity = null;
						previousValue.Table_CauHois.Remove(this);
					}
					this._Table_MonThi.Entity = value;
					if ((value != null))
					{
						value.Table_CauHois.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(string);
					}
					this.SendPropertyChanged("Table_MonThi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NguoiDung_Table_CauHoi", Storage="_Table_NguoiDung", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung", IsForeignKey=true)]
		public Table_NguoiDung Table_NguoiDung
		{
			get
			{
				return this._Table_NguoiDung.Entity;
			}
			set
			{
				Table_NguoiDung previousValue = this._Table_NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._Table_NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_NguoiDung.Entity = null;
						previousValue.Table_CauHois.Remove(this);
					}
					this._Table_NguoiDung.Entity = value;
					if ((value != null))
					{
						value.Table_CauHois.Add(this);
						this._MaNguoiDung = value.MaNguoiDung;
					}
					else
					{
						this._MaNguoiDung = default(string);
					}
					this.SendPropertyChanged("Table_NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_DapAns(Table_DapAn entity)
		{
			this.SendPropertyChanging();
			entity.Table_CauHoi = this;
		}
		
		private void detach_Table_DapAns(Table_DapAn entity)
		{
			this.SendPropertyChanging();
			entity.Table_CauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_DapAn")]
	public partial class Table_DapAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCauTraLoi;
		
		private string _NoiDungCauTraLoi;
		
		private string _MaCauHoi;
		
		private string _KieuDapAn;
		
		private EntityRef<Table_CauHoi> _Table_CauHoi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauTraLoiChanging(string value);
    partial void OnMaCauTraLoiChanged();
    partial void OnNoiDungCauTraLoiChanging(string value);
    partial void OnNoiDungCauTraLoiChanged();
    partial void OnMaCauHoiChanging(string value);
    partial void OnMaCauHoiChanged();
    partial void OnKieuDapAnChanging(string value);
    partial void OnKieuDapAnChanged();
    #endregion
		
		public Table_DapAn()
		{
			this._Table_CauHoi = default(EntityRef<Table_CauHoi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauTraLoi", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCauTraLoi
		{
			get
			{
				return this._MaCauTraLoi;
			}
			set
			{
				if ((this._MaCauTraLoi != value))
				{
					this.OnMaCauTraLoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauTraLoi = value;
					this.SendPropertyChanged("MaCauTraLoi");
					this.OnMaCauTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCauTraLoi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NoiDungCauTraLoi
		{
			get
			{
				return this._NoiDungCauTraLoi;
			}
			set
			{
				if ((this._NoiDungCauTraLoi != value))
				{
					this.OnNoiDungCauTraLoiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCauTraLoi = value;
					this.SendPropertyChanged("NoiDungCauTraLoi");
					this.OnNoiDungCauTraLoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					if (this._Table_CauHoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KieuDapAn", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string KieuDapAn
		{
			get
			{
				return this._KieuDapAn;
			}
			set
			{
				if ((this._KieuDapAn != value))
				{
					this.OnKieuDapAnChanging(value);
					this.SendPropertyChanging();
					this._KieuDapAn = value;
					this.SendPropertyChanged("KieuDapAn");
					this.OnKieuDapAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_CauHoi_Table_DapAn", Storage="_Table_CauHoi", ThisKey="MaCauHoi", OtherKey="MaCauHoi", IsForeignKey=true)]
		public Table_CauHoi Table_CauHoi
		{
			get
			{
				return this._Table_CauHoi.Entity;
			}
			set
			{
				Table_CauHoi previousValue = this._Table_CauHoi.Entity;
				if (((previousValue != value) 
							|| (this._Table_CauHoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_CauHoi.Entity = null;
						previousValue.Table_DapAns.Remove(this);
					}
					this._Table_CauHoi.Entity = value;
					if ((value != null))
					{
						value.Table_DapAns.Add(this);
						this._MaCauHoi = value.MaCauHoi;
					}
					else
					{
						this._MaCauHoi = default(string);
					}
					this.SendPropertyChanged("Table_CauHoi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_GiaoVien")]
	public partial class Table_GiaoVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaGiaoVien;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private string _NgaySinh;
		
		private string _ChucVu;
		
		private EntitySet<Table_NguoiDung> _Table_NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaGiaoVienChanging(string value);
    partial void OnMaGiaoVienChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    #endregion
		
		public Table_GiaoVien()
		{
			this._Table_NguoiDungs = new EntitySet<Table_NguoiDung>(new Action<Table_NguoiDung>(this.attach_Table_NguoiDungs), new Action<Table_NguoiDung>(this.detach_Table_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoVien", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaGiaoVien
		{
			get
			{
				return this._MaGiaoVien;
			}
			set
			{
				if ((this._MaGiaoVien != value))
				{
					this.OnMaGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVien = value;
					this.SendPropertyChanged("MaGiaoVien");
					this.OnMaGiaoVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_GiaoVien_Table_NguoiDung", Storage="_Table_NguoiDungs", ThisKey="MaGiaoVien", OtherKey="MaGiaoVien")]
		public EntitySet<Table_NguoiDung> Table_NguoiDungs
		{
			get
			{
				return this._Table_NguoiDungs;
			}
			set
			{
				this._Table_NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_NguoiDungs(Table_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Table_GiaoVien = this;
		}
		
		private void detach_Table_NguoiDungs(Table_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.Table_GiaoVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_KetQua")]
	public partial class Table_KetQua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThiSinh;
		
		private string _MaMon;
		
		private double _Diem;
		
		private string _NgayThi;
		
		private EntityRef<Table_MonThi> _Table_MonThi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThiSinhChanging(string value);
    partial void OnMaThiSinhChanged();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnDiemChanging(double value);
    partial void OnDiemChanged();
    partial void OnNgayThiChanging(string value);
    partial void OnNgayThiChanged();
    #endregion
		
		public Table_KetQua()
		{
			this._Table_MonThi = default(EntityRef<Table_MonThi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThiSinh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThiSinh
		{
			get
			{
				return this._MaThiSinh;
			}
			set
			{
				if ((this._MaThiSinh != value))
				{
					this.OnMaThiSinhChanging(value);
					this.SendPropertyChanging();
					this._MaThiSinh = value;
					this.SendPropertyChanged("MaThiSinh");
					this.OnMaThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._Table_MonThi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diem", DbType="Float NOT NULL")]
		public double Diem
		{
			get
			{
				return this._Diem;
			}
			set
			{
				if ((this._Diem != value))
				{
					this.OnDiemChanging(value);
					this.SendPropertyChanging();
					this._Diem = value;
					this.SendPropertyChanged("Diem");
					this.OnDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThi", DbType="NChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NgayThi
		{
			get
			{
				return this._NgayThi;
			}
			set
			{
				if ((this._NgayThi != value))
				{
					this.OnNgayThiChanging(value);
					this.SendPropertyChanging();
					this._NgayThi = value;
					this.SendPropertyChanged("NgayThi");
					this.OnNgayThiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_MonThi_Table_KetQua", Storage="_Table_MonThi", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public Table_MonThi Table_MonThi
		{
			get
			{
				return this._Table_MonThi.Entity;
			}
			set
			{
				Table_MonThi previousValue = this._Table_MonThi.Entity;
				if (((previousValue != value) 
							|| (this._Table_MonThi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_MonThi.Entity = null;
						previousValue.Table_KetQuas.Remove(this);
					}
					this._Table_MonThi.Entity = value;
					if ((value != null))
					{
						value.Table_KetQuas.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(string);
					}
					this.SendPropertyChanged("Table_MonThi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_LoaiCauHoi")]
	public partial class Table_LoaiCauHoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiCauHoi;
		
		private string _LoaiCauHoi;
		
		private EntitySet<Table_CauHoi> _Table_CauHois;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiCauHoiChanging(string value);
    partial void OnMaLoaiCauHoiChanged();
    partial void OnLoaiCauHoiChanging(string value);
    partial void OnLoaiCauHoiChanged();
    #endregion
		
		public Table_LoaiCauHoi()
		{
			this._Table_CauHois = new EntitySet<Table_CauHoi>(new Action<Table_CauHoi>(this.attach_Table_CauHois), new Action<Table_CauHoi>(this.detach_Table_CauHois));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiCauHoi", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiCauHoi
		{
			get
			{
				return this._MaLoaiCauHoi;
			}
			set
			{
				if ((this._MaLoaiCauHoi != value))
				{
					this.OnMaLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiCauHoi = value;
					this.SendPropertyChanged("MaLoaiCauHoi");
					this.OnMaLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiCauHoi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiCauHoi
		{
			get
			{
				return this._LoaiCauHoi;
			}
			set
			{
				if ((this._LoaiCauHoi != value))
				{
					this.OnLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._LoaiCauHoi = value;
					this.SendPropertyChanged("LoaiCauHoi");
					this.OnLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_LoaiCauHoi_Table_CauHoi", Storage="_Table_CauHois", ThisKey="MaLoaiCauHoi", OtherKey="MaLoaiCauHoi")]
		public EntitySet<Table_CauHoi> Table_CauHois
		{
			get
			{
				return this._Table_CauHois;
			}
			set
			{
				this._Table_CauHois.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_CauHois(Table_CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.Table_LoaiCauHoi = this;
		}
		
		private void detach_Table_CauHois(Table_CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.Table_LoaiCauHoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_MonThi")]
	public partial class Table_MonThi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMon;
		
		private string _TenMon;
		
		private EntitySet<Table_CauHoi> _Table_CauHois;
		
		private EntitySet<Table_KetQua> _Table_KetQuas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(string value);
    partial void OnMaMonChanged();
    partial void OnTenMonChanging(string value);
    partial void OnTenMonChanged();
    #endregion
		
		public Table_MonThi()
		{
			this._Table_CauHois = new EntitySet<Table_CauHoi>(new Action<Table_CauHoi>(this.attach_Table_CauHois), new Action<Table_CauHoi>(this.detach_Table_CauHois));
			this._Table_KetQuas = new EntitySet<Table_KetQua>(new Action<Table_KetQua>(this.attach_Table_KetQuas), new Action<Table_KetQua>(this.detach_Table_KetQuas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this.OnTenMonChanging(value);
					this.SendPropertyChanging();
					this._TenMon = value;
					this.SendPropertyChanged("TenMon");
					this.OnTenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_MonThi_Table_CauHoi", Storage="_Table_CauHois", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<Table_CauHoi> Table_CauHois
		{
			get
			{
				return this._Table_CauHois;
			}
			set
			{
				this._Table_CauHois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_MonThi_Table_KetQua", Storage="_Table_KetQuas", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<Table_KetQua> Table_KetQuas
		{
			get
			{
				return this._Table_KetQuas;
			}
			set
			{
				this._Table_KetQuas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_CauHois(Table_CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.Table_MonThi = this;
		}
		
		private void detach_Table_CauHois(Table_CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.Table_MonThi = null;
		}
		
		private void attach_Table_KetQuas(Table_KetQua entity)
		{
			this.SendPropertyChanging();
			entity.Table_MonThi = this;
		}
		
		private void detach_Table_KetQuas(Table_KetQua entity)
		{
			this.SendPropertyChanging();
			entity.Table_MonThi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_Nganh")]
	public partial class Table_Nganh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNganh;
		
		private string _TenNganh;
		
		private EntitySet<Table_ThiSinh> _Table_ThiSinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNganhChanging(string value);
    partial void OnMaNganhChanged();
    partial void OnTenNganhChanging(string value);
    partial void OnTenNganhChanged();
    #endregion
		
		public Table_Nganh()
		{
			this._Table_ThiSinhs = new EntitySet<Table_ThiSinh>(new Action<Table_ThiSinh>(this.attach_Table_ThiSinhs), new Action<Table_ThiSinh>(this.detach_Table_ThiSinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					this.OnMaNganhChanging(value);
					this.SendPropertyChanging();
					this._MaNganh = value;
					this.SendPropertyChanged("MaNganh");
					this.OnMaNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNganh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNganh
		{
			get
			{
				return this._TenNganh;
			}
			set
			{
				if ((this._TenNganh != value))
				{
					this.OnTenNganhChanging(value);
					this.SendPropertyChanging();
					this._TenNganh = value;
					this.SendPropertyChanged("TenNganh");
					this.OnTenNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_Nganh_Table_ThiSinh", Storage="_Table_ThiSinhs", ThisKey="MaNganh", OtherKey="MaNganh")]
		public EntitySet<Table_ThiSinh> Table_ThiSinhs
		{
			get
			{
				return this._Table_ThiSinhs;
			}
			set
			{
				this._Table_ThiSinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_ThiSinhs(Table_ThiSinh entity)
		{
			this.SendPropertyChanging();
			entity.Table_Nganh = this;
		}
		
		private void detach_Table_ThiSinhs(Table_ThiSinh entity)
		{
			this.SendPropertyChanging();
			entity.Table_Nganh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_NguoiDung")]
	public partial class Table_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNguoiDung;
		
		private string _TenNguoiDung;
		
		private string _MatKhauNguoiDung;
		
		private string _LoaiNguoiDung;
		
		private string _MaGiaoVien;
		
		private EntitySet<Table_CauHoi> _Table_CauHois;
		
		private EntityRef<Table_GiaoVien> _Table_GiaoVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNguoiDungChanging(string value);
    partial void OnMaNguoiDungChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnMatKhauNguoiDungChanging(string value);
    partial void OnMatKhauNguoiDungChanged();
    partial void OnLoaiNguoiDungChanging(string value);
    partial void OnLoaiNguoiDungChanged();
    partial void OnMaGiaoVienChanging(string value);
    partial void OnMaGiaoVienChanged();
    #endregion
		
		public Table_NguoiDung()
		{
			this._Table_CauHois = new EntitySet<Table_CauHoi>(new Action<Table_CauHoi>(this.attach_Table_CauHois), new Action<Table_CauHoi>(this.detach_Table_CauHois));
			this._Table_GiaoVien = default(EntityRef<Table_GiaoVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiDung", DbType="NChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNguoiDung
		{
			get
			{
				return this._MaNguoiDung;
			}
			set
			{
				if ((this._MaNguoiDung != value))
				{
					this.OnMaNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiDung = value;
					this.SendPropertyChanged("MaNguoiDung");
					this.OnMaNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhauNguoiDung", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhauNguoiDung
		{
			get
			{
				return this._MatKhauNguoiDung;
			}
			set
			{
				if ((this._MatKhauNguoiDung != value))
				{
					this.OnMatKhauNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MatKhauNguoiDung = value;
					this.SendPropertyChanged("MatKhauNguoiDung");
					this.OnMatKhauNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNguoiDung", DbType="NChar(6) NOT NULL", CanBeNull=false)]
		public string LoaiNguoiDung
		{
			get
			{
				return this._LoaiNguoiDung;
			}
			set
			{
				if ((this._LoaiNguoiDung != value))
				{
					this.OnLoaiNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._LoaiNguoiDung = value;
					this.SendPropertyChanged("LoaiNguoiDung");
					this.OnLoaiNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaGiaoVien", DbType="NChar(4) NOT NULL", CanBeNull=false)]
		public string MaGiaoVien
		{
			get
			{
				return this._MaGiaoVien;
			}
			set
			{
				if ((this._MaGiaoVien != value))
				{
					if (this._Table_GiaoVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaGiaoVienChanging(value);
					this.SendPropertyChanging();
					this._MaGiaoVien = value;
					this.SendPropertyChanged("MaGiaoVien");
					this.OnMaGiaoVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_NguoiDung_Table_CauHoi", Storage="_Table_CauHois", ThisKey="MaNguoiDung", OtherKey="MaNguoiDung")]
		public EntitySet<Table_CauHoi> Table_CauHois
		{
			get
			{
				return this._Table_CauHois;
			}
			set
			{
				this._Table_CauHois.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_GiaoVien_Table_NguoiDung", Storage="_Table_GiaoVien", ThisKey="MaGiaoVien", OtherKey="MaGiaoVien", IsForeignKey=true)]
		public Table_GiaoVien Table_GiaoVien
		{
			get
			{
				return this._Table_GiaoVien.Entity;
			}
			set
			{
				Table_GiaoVien previousValue = this._Table_GiaoVien.Entity;
				if (((previousValue != value) 
							|| (this._Table_GiaoVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_GiaoVien.Entity = null;
						previousValue.Table_NguoiDungs.Remove(this);
					}
					this._Table_GiaoVien.Entity = value;
					if ((value != null))
					{
						value.Table_NguoiDungs.Add(this);
						this._MaGiaoVien = value.MaGiaoVien;
					}
					else
					{
						this._MaGiaoVien = default(string);
					}
					this.SendPropertyChanged("Table_GiaoVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Table_CauHois(Table_CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.Table_NguoiDung = this;
		}
		
		private void detach_Table_CauHois(Table_CauHoi entity)
		{
			this.SendPropertyChanging();
			entity.Table_NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_ThiSinh")]
	public partial class Table_ThiSinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThiSinh;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private string _NgaySinh;
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _Truong;
		
		private string _Lop;
		
		private string _MaNganh;
		
		private EntityRef<Table_Nganh> _Table_Nganh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThiSinhChanging(string value);
    partial void OnMaThiSinhChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTruongChanging(string value);
    partial void OnTruongChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    partial void OnMaNganhChanging(string value);
    partial void OnMaNganhChanged();
    #endregion
		
		public Table_ThiSinh()
		{
			this._Table_Nganh = default(EntityRef<Table_Nganh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThiSinh", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThiSinh
		{
			get
			{
				return this._MaThiSinh;
			}
			set
			{
				if ((this._MaThiSinh != value))
				{
					this.OnMaThiSinhChanging(value);
					this.SendPropertyChanging();
					this._MaThiSinh = value;
					this.SendPropertyChanged("MaThiSinh");
					this.OnMaThiSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Truong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Truong
		{
			get
			{
				return this._Truong;
			}
			set
			{
				if ((this._Truong != value))
				{
					this.OnTruongChanging(value);
					this.SendPropertyChanging();
					this._Truong = value;
					this.SendPropertyChanged("Truong");
					this.OnTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNganh", DbType="NChar(10)")]
		public string MaNganh
		{
			get
			{
				return this._MaNganh;
			}
			set
			{
				if ((this._MaNganh != value))
				{
					if (this._Table_Nganh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNganhChanging(value);
					this.SendPropertyChanging();
					this._MaNganh = value;
					this.SendPropertyChanged("MaNganh");
					this.OnMaNganhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Table_Nganh_Table_ThiSinh", Storage="_Table_Nganh", ThisKey="MaNganh", OtherKey="MaNganh", IsForeignKey=true)]
		public Table_Nganh Table_Nganh
		{
			get
			{
				return this._Table_Nganh.Entity;
			}
			set
			{
				Table_Nganh previousValue = this._Table_Nganh.Entity;
				if (((previousValue != value) 
							|| (this._Table_Nganh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Table_Nganh.Entity = null;
						previousValue.Table_ThiSinhs.Remove(this);
					}
					this._Table_Nganh.Entity = value;
					if ((value != null))
					{
						value.Table_ThiSinhs.Add(this);
						this._MaNganh = value.MaNganh;
					}
					else
					{
						this._MaNganh = default(string);
					}
					this.SendPropertyChanged("Table_Nganh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
